// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWVjHrEX8LvSkpK7WsAqDdYqrfmK7xZVA',
    appId: '1:128345461392:web:67571f5528099afc5bfe15',
    messagingSenderId: '128345461392',
    projectId: 'ecommerceapp-8d99f',
    authDomain: 'ecommerceapp-8d99f.firebaseapp.com',
    storageBucket: 'ecommerceapp-8d99f.appspot.com',
    measurementId: 'G-KNF0BPGJ18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZFjEV3CruihWhXlnXcuAzglp9jx8jPsw',
    appId: '1:128345461392:android:7bd109fe5071c2765bfe15',
    messagingSenderId: '128345461392',
    projectId: 'ecommerceapp-8d99f',
    storageBucket: 'ecommerceapp-8d99f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFrh65YAAiSduAaqRLcAKkK_J6N-5UGbU',
    appId: '1:128345461392:ios:f596168d2af112625bfe15',
    messagingSenderId: '128345461392',
    projectId: 'ecommerceapp-8d99f',
    storageBucket: 'ecommerceapp-8d99f.appspot.com',
    androidClientId: '128345461392-abu5ffefm3u78h4at9memd1qtpkshruq.apps.googleusercontent.com',
    iosClientId: '128345461392-qq9kvatq0r28r2qbrg6m9puakknuc27k.apps.googleusercontent.com',
    iosBundleId: 'com.example.lStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWVjHrEX8LvSkpK7WsAqDdYqrfmK7xZVA',
    appId: '1:128345461392:web:d7754e88c1c52c075bfe15',
    messagingSenderId: '128345461392',
    projectId: 'ecommerceapp-8d99f',
    authDomain: 'ecommerceapp-8d99f.firebaseapp.com',
    storageBucket: 'ecommerceapp-8d99f.appspot.com',
    measurementId: 'G-5X3MNFHD3W',
  );

}