name: l_store
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1


#------ PACKAGES -----------#

dependencies:
  flutter:
    sdk: flutter

  #Utlity packages
  http: ^1.2.2
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  
  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  carousel_slider: ^5.0.0

  #Product Specific
  readmore: ^3.0.0

#---------- PACKAGES END -----------#


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

#---------- LOCAL ASSETS -----------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
  
#---------- LOCAL FONTS -----------#
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800
        

  uses-material-design: true

